[workspace]
members = [
    "ppproto",
    "example",
]

[patch.crates-io]
smoltcp = { git = "https://github.com/akiles/smoltcp", branch="master"}
anyfmt = { git = "https://github.com/akiles/embassy" }
defmt = { git = "https://github.com/knurling-rs/defmt", branch="main" }
