[package]
name = "ppproto"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[dependencies]
num_enum = { version = "0.5.1" }
managed = { version = "0.8.0", default-features = false }
log = "0.4.11"
smoltcp = "0.6.0"
