[package]
name = "ppproto"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = ["defmt/alloc"]
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
num_enum = { version = "0.5.1", default-features = false }
smoltcp = { version = "0.6.0", default-features = false, features = [ "proto-ipv4", "defmt"] }
defmt = { version = "0.1.3" }
as-slice = "0.1.4"
heapless = "0.5.6"
